// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkcLWxh7zXXr_SCL1ssASvz4Nm1TYdrQU',
    appId: '1:1006130066125:web:5a5749b380703132e12f84',
    messagingSenderId: '1006130066125',
    projectId: 'smart-women-safety-app-b1988',
    authDomain: 'smart-women-safety-app-b1988.firebaseapp.com',
    databaseURL: 'https://smart-women-safety-app-b1988-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-women-safety-app-b1988.firebasestorage.app',
    measurementId: 'G-8XG5V7QW04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChOh0tTNSviSn2Z13Jipr33tEmFCJKewI',
    appId: '1:1006130066125:android:3141c9648f3c78d4e12f84',
    messagingSenderId: '1006130066125',
    projectId: 'smart-women-safety-app-b1988',
    databaseURL: 'https://smart-women-safety-app-b1988-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-women-safety-app-b1988.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ2Vgn270WHvvEija5SEFC6MyTKyomQMU',
    appId: '1:1006130066125:ios:d9ab5703fa717735e12f84',
    messagingSenderId: '1006130066125',
    projectId: 'smart-women-safety-app-b1988',
    databaseURL: 'https://smart-women-safety-app-b1988-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-women-safety-app-b1988.firebasestorage.app',
    iosBundleId: 'com.example.smartSafetyApp',
  );
}